### ISSUE TITLE
Does...nothing?

### ISSUE THREAD

**Issue by spinetree** [ahmedmigo/Move-to-library-sketchplugin#1]
Latest version of sketch, tried running on a symbol instance on a page and also on a symbol on the symbols page. Can't get it to do anything. Restarted sketch since install, still no dice.

**Comment by ahmedmigo** [comment]
hello @spinetree can you send me your file that is not working to trace your error ?

**Comment by spinetree** [comment]
'Fraid not, it's all proprietary stuff. I'm on OSX, latest High Sierra,
everything's up to date.

Best,
Steve Rokitka

(607) 431-8733
s <steve@spinetree.org>pinetree@gmail.com

**Comment by ahmedmigo** [comment]
is this appearing with you with all symbols ?
and can you open console and in the search filled write "sketch" and copy and past the log for me so i can trace your error and fix it ?

**Comment by josealvarezn** [comment]
Hi, Ahmed!
I found a little issue with the plugin (probably the same issue), when you move any symbol to a library, the Symbol page has some issues with the elements moved. Basically, the moved elements are frozen!
Thank very much!

**Comment by ahmedmigo** [comment]
@josealvarezn  I recognized this issue and i will be working on solving it, but for quick work around just restart your sketch file and it will work fine. feel free to get back to me if you find any trouble.

**Comment by ahmedmigo** [comment]
@josealvarezn hello my friend the problem solved in the new update please update the plugin and give me your feedback

**Comment by josealvarezn** [comment]
Hi, @ahmedmigo! I just updated and tested, but the problem persists and had another issue, the moved symbol was duplicated on the Symbol Page.

Thanks for your amazing support!
![image](https://user-images.githubusercontent.com/16816916/35155560-5d749a80-fd04-11e7-93b1-a179089f6d25.png)

**Comment by ahmedmigo** [comment]
this is may be because they have the same name I will check this issue and get back to you again

**Comment by ahmedmigo** [comment]
@josealvarezn I reverted it to the older version with some fixes for the nested symbols
I will keep the issue open to figure out this later

**Comment by ahmedmigo** [comment]
a quick solve is to restart your file after using the plugin

**Comment by ahmedmigo** [comment]
Issue Solved
