### ISSUE TITLE
Is this plugin working in Sketch 54?

### ISSUE THREAD

**Issue by oskondric** [ahmedmigo/Move-to-library-sketchplugin#22]
I would really like to use this plugin... but it seams like it's not working at all in Sketch 54. Is this a known issue?

<img width="722" alt="Move_to_library_and__ele__buttons__lib-plug-test__sketch" src="https://user-images.githubusercontent.com/48978371/56094496-547c7b80-5ed5-11e9-9da8-d9c43b99221a.png">

**Comment by ahmedmigo** [comment]
this issue is fixed in the new version, if not please delete the plugin and redownload it again. from this link
https://github.com/ahmedmigo/Move-to-library-sketchplugin/archive/master.zip

**Comment by oskondric** [comment]
Unfortunately it still doesn't work for me. I removed the previous version of the plugin and installed the new one from the link that you provided. I still got the black screen as seen above.

**Comment by ahmedmigo** [comment]
@oskondric can you try again, I just pushed a new update. 
I hope it works

**Comment by oskondric** [comment]
it worked :))...super happy.... donated 20€... thanks

**Comment by ahmedmigo** [comment]
@oskondric Thank you so much :)
