### ISSUE TITLE
Not working with Sketch 51?

### ISSUE THREAD

**Issue by romanr** [ahmedmigo/Move-to-library-sketchplugin#9]
Nothing happens when Library is selected and button is pressed. Is it broken again by Sketch internal file structure changes?

**Comment by ahmedmigo** [comment]
Hello, 
yes there is some problems with the new version of sketch and I am working on the new update soon :)

**Comment by ahmedmigo** [comment]
Hello @romanr 
I released a new updated.
can you update and test it and tell me ?

**Comment by romanr** [comment]
With plugin version 2.0.4 it still don't work. Is there a newer version?
